# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 4);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1474572060);
user_pref("browser.laterrun.bookkeeping.sessionCount", 3);
user_pref("browser.migration.version", 37);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1493840144408");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1493843744408");
user_pref("browser.search.countryCode", "BR");
user_pref("browser.search.region", "BR");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20160817112116");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1493840211");
user_pref("browser.slowStartup.averageTime", 7099);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20160817112116");
user_pref("browser.startup.homepage_override.mstone", "48.0.1");
user_pref("browser.taskbar.lastgroupid", "E7CF176E110C211B");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\",\"sync-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"downloads-button\",\"home-button\",\"loop-button\",\"pocket-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"loop-button\",\"pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\",\"PanelUI-contents\",\"addon-bar\"],\"currentVersion\":6,\"newElementCount\":0}");
user_pref("browser.urlbar.daysBeforeHidingSuggestionsPrompt", 2);
user_pref("browser.urlbar.lastSuggestionsPromptDate", 20170503);
user_pref("browser.usedOnWindows10", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1474658066670");
user_pref("datareporting.sessions.current.activeTicks", 4);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 5021);
user_pref("datareporting.sessions.current.main", 1598);
user_pref("datareporting.sessions.current.sessionRestored", 5261);
user_pref("datareporting.sessions.current.startTime", "1493840206116");
user_pref("datareporting.sessions.current.totalTime", 21);
user_pref("datareporting.sessions.currentIndex", 3);
user_pref("datareporting.sessions.previous.0", "{\"s\":1474572054966,\"a\":5,\"t\":31,\"c\":true,\"m\":1724,\"fp\":6245,\"sr\":10315}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1474658048885,\"a\":3,\"t\":18,\"c\":true,\"m\":4317,\"fp\":7600,\"sr\":7790}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1493840130390,\"a\":7,\"t\":39,\"c\":true,\"m\":1552,\"fp\":4619,\"sr\":6353}");
user_pref("dom.apps.reset-permissions", true);
user_pref("e10s.rollout.cohort", "control");
user_pref("e10s.rollout.cohortSample", "0.591320");
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{\"e10srollout@mozilla.org\":{\"version\":\"1.1\",\"type\":\"extension\",\"descriptor\":\"C:\\\\Program Files (x86)\\\\Mozilla Firefox\\\\browser\\\\features\\\\e10srollout@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true},\"firefox@getpocket.com\":{\"version\":\"1.0.4\",\"type\":\"extension\",\"descriptor\":\"C:\\\\Program Files (x86)\\\\Mozilla Firefox\\\\browser\\\\features\\\\firefox@getpocket.com.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true},\"loop@mozilla.org\":{\"version\":\"1.4.4\",\"type\":\"extension\",\"descriptor\":\"C:\\\\Program Files (x86)\\\\Mozilla Firefox\\\\browser\\\\features\\\\loop@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.e10sBlockedByAddons", false);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:48.0.1");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "48.0.1");
user_pref("extensions.lastPlatformVersion", "48.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-system-defaults\":{\"e10srollout@mozilla.org\":{\"d\":\"C:\\\\Program Files (x86)\\\\Mozilla Firefox\\\\browser\\\\features\\\\e10srollout@mozilla.org.xpi\",\"e\":true,\"v\":\"1.1\",\"st\":1472041263841},\"firefox@getpocket.com\":{\"d\":\"C:\\\\Program Files (x86)\\\\Mozilla Firefox\\\\browser\\\\features\\\\firefox@getpocket.com.xpi\",\"e\":true,\"v\":\"1.0.4\",\"st\":1472041263838},\"loop@mozilla.org\":{\"d\":\"C:\\\\Program Files (x86)\\\\Mozilla Firefox\\\\browser\\\\features\\\\loop@mozilla.org.xpi\",\"e\":true,\"v\":\"1.4.4\",\"st\":1472041263832}},\"winreg-app-user\":{\"{87F8774F-B485-47E2-A755-A40A8A5E8874}\":{\"d\":\"C:\\\\Users\\\\ggodoy\\\\AppData\\\\Local\\\\GAS Tecnologia\\\\GBBD\\\\abn\\\\xpi\",\"e\":false,\"v\":\"3.5.2\",\"st\":1427126002858,\"mt\":1427126002858}},\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"C:\\\\Program Files (x86)\\\\Mozilla Firefox\\\\browser\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"48.0.1\",\"st\":1472041263866}}}");
user_pref("gecko.buildID", "20160817112116");
user_pref("gecko.mstone", "48.0.1");
user_pref("gfx.crash-guard.d3d11layers.appVersion", "48.0.1");
user_pref("gfx.crash-guard.d3d11layers.deviceID", "0x0412");
user_pref("gfx.crash-guard.d3d11layers.driverVersion", "20.19.15.4624");
user_pref("gfx.crash-guard.d3d11layers.feature-d2d", true);
user_pref("gfx.crash-guard.d3d11layers.feature-d3d11", true);
user_pref("gfx.crash-guard.status.", 2);
user_pref("gfx.crash-guard.status.d3d11layers", 2);
user_pref("gfx.crash-guard.status.d3d9video", 2);
user_pref("loop.copy.ticket", 225);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("sanity-test.device-id", "0x0412");
user_pref("sanity-test.driver-version", "20.19.15.4624");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20160817112116");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1493840207);
user_pref("toolkit.telemetry.previousBuildID", "20160817112116");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("ui.osk.debug.keyboardDisplayReason", "IKPOS: Touch screen not found.");
